### ISSUE TITLE
World Locking

### ISSUE THREAD

**Issue by Tristan360x** [MutinyCraft/AntiBuild#1]
I currently use your plugin during events and to keep new players from building until they have registered to play on the server.  During events, I lock the world to prevent building, specifically during what we call "Infernal Friday's" where we have extremely hardcore mobs.  I want players to be able to access chests, be able to pick up items, and use potions, but still not build.  When I lock the world, it does it what I believe was intended, but prevents the above completely.  Maybe I have something wrong in the permissions (players with a rank have the bypass permission).

Is there a way to allow players to do the above but prevent building completely?

**Comment by MutinyCraft** [comment]
Currently there is no way to customize what the world lock controls.  As you have seen it simply disables everything in the locked world unless you have permission to bypass it.  My recommendation, for the time being, would be to simply use the different permission nodes to achieve your desired outcome with AntiBuild.  This would mean giving the players every permission except the place and break permissions in that world.  

If you would still like me to add the ability to only lock building in the world I can look into that.  It may not be done right away, but it shouldn't be too hard to do.  Feel free to take a look at the source code and make the changes if that is something you would like to do.

**Comment by Tristan360x** [comment]
That would be awesome if you could.  I spoke to my staff about it which is why it has taken me  a little bit to respond.  We all agree that it would be nice if you could add the ability to lock the world but allow access to certain and or other items (chests and potions)

**Comment by MutinyCraft** [comment]
Give this a try.

https://github.com/MutinyCraft/AntiBuild-Old/releases/tag/2.9.3

**Comment by Tristan360x** [comment]
Hi!
Thanks so much, it seems to work very well.  In last nights testing, players were able to access chests and so forth, but the world was locked to building.  I will update you if further issues do arise.

Great works and thanks again! :)

Clay

**Comment by MutinyCraft** [comment]
That's good to hear.
