### ISSUE TITLE
Permissions antibuild.lock.example

### ISSUE THREAD

**Issue by MrDr4gon** [MutinyCraft/AntiBuild#4]
Hi!
I've got locked the world and now, people without permission "antibuild.lock.bypass" couldn't open chests and interact with other items. Could you create permission "antibuild.lock.interact" or maybe "antibuild.lock.chest"? I'll really happy. Thanks! 

---

I know, my awesome English is awesome! ;3

**Comment by MutinyCraft** [comment]
Yes, this is a planned feature.  It should be implemented in the next few days.

**Comment by MrDr4gon** [comment]
Ohh, it's really cool to hear it. Good luck! :)

**Comment by MutinyCraft** [comment]
Give this a try.

https://github.com/MutinyCraft/AntiBuild-Old/releases/tag/2.9.3

**Comment by MrDr4gon** [comment]
Thanks :)
